services:
  - type: web
    name: teddy-xmd
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: PREFIX
        sync: false
